# Generated by Django 2.2.3 on 2020-01-13 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0008_auto_20200113_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='evolution',
            new_name='previous_evolution',
        ),
    ]
