# Generated by Django 2.2.3 on 2020-01-13 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0009_auto_20200113_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='previous_evolution',
            new_name='evolution',
        ),
    ]
