# Generated by Django 2.2.3 on 2020-01-14 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0014_auto_20200114_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='evolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pokemon_evolution', to='pokemon_entities.Pokemon', verbose_name='эволюция  покемонов'),
        ),
    ]
