# Generated by Django 2.2.3 on 2020-01-18 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0015_auto_20200114_2120'),
    ]

    operations = [
    ]
