# Generated by Django 2.2.3 on 2020-01-18 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0017_auto_20200118_1903'),
    ]

    operations = [
    ]
