# Generated by Django 2.2.3 on 2020-01-19 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0019_auto_20200118_1918'),
    ]

    operations = [
    ]
