# Generated by Django 2.2.3 on 2020-01-20 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0020_auto_20200119_1022'),
    ]

    operations = [
    ]
