# Generated by Django 2.2.3 on 2020-01-20 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0021_auto_20200120_1857'),
    ]

    operations = [
    ]
